### ISSUE TITLE
How does this relate to pi-forall?

### ISSUE THREAD

**Issue by samuelgruetter** [marklemay/calculus-of-constructions#4]
This project reminds me of Stephanie Weirich's pi-forall: https://github.com/sweirich/pi-forall

So I wonder: are these two based on the same theoretical foundations, or what are the differences?

**Comment by marklemay** [comment]
That project seems to create a nice agda/haskell like language.  It allows for datatypes.

Both projects are based on the same foundations (pure type systems), but this project commits to only those (at the programmer's expense).

This project is more aggressively minimal (there is a 100 line core), is written in scala instead of haskell, and has many more spelling errors.

**Comment by marklemay** [comment]
Also it is not the case the type:type in this project.   Except for int overflow, this project should be sound.

**Comment by samuelgruetter** [comment]
Thanks for the comparison, that's very helpful. In particular, I find it cool that you don't do type:type, and I didn't notice that at originally.
